#!/usr/bin/env sh
# Set locale to avoid warnings
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
npm run lint
# Skip flaky CLI integration tests in pre-commit
npm test -- --testPathIgnorePatterns="tests/integration/cli.test.js"
